%%{
    init: {
        "theme" : "neutral",
        "class": {
            "hideEmptyMembersBox": true
        }
    }
}%%
classDiagram
    class VerifiableCredential {
        credentialSubject: URL
        validFrom: xsd.datTime
        validUntil: xsd.datTime
        relatedResource: URL
        issuer: URL
    }

    class CredentialSchema {}
    class CredentialStatus {}
    class CredentialEvidence {}
    class RefreshService {}
    class RenderMethod {}
    class ConfidenceMethod {}
    class TermOfUse {}

    class JsonSchemaCredential {}
    class VerifiableCredentialGraph {}

    class EnvelopedVerifiablePresentation {}
    class EnvelopedVerifiableCredential {}
    class VerifiablePresentation {
        holder: URL
        validFrom: xsd.datTime
        validUntil: xsd.dateTime
    }
    class JsonSchema {
        jsonSchema: rdf.JSON
    }

    JsonSchemaCredential --|> VerifiableCredential : rdfs.subClassOf
    JsonSchema --|> CredentialSchema : rdfs.subClassOf

    VerifiableCredential --> CredentialSchema : credentialSchema
    VerifiableCredential --> CredentialStatus : credentialStatus
    VerifiableCredential --> CredentialEvidence : evidence
    VerifiableCredential --> RefreshService : refreshService
    VerifiableCredential --> RenderMethod : renderMethod
    VerifiableCredential --> ConfidenceMethod : confidenceMethod
    VerifiableCredential --> TermOfUse : termOfUse

    VerifiablePresentation --> TermOfUse : termOfUse
    VerifiablePresentation --> VerifiableCredentialGraph : verifiableCredential

    VerifiableCredentialGraph ..> VerifiableCredential
    VerifiableCredentialGraph ..> EnvelopedVerifiableCredential

