name: Automatic Generation of Vocabulary Files
on:
  push:
    branches: [main]
    paths: ["vocab/credentials/v2/vocabulary.yml", "vocab/credentials/v2/template.html"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout/@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install and run the yml2vocab script
        run: |
          npm install yml2vocab
          npm update yml2vocab
          ./node_modules/.bin/yml2vocab -v vocab/credentials/v2/vocabulary.yml -t vocab/credentials/v2/template.html
      - name: Deploy to gh-pages branches
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
          git-config-name: "vcwg[bot]"
          git-config-email: "vcwg[bot]@users.noreply.github.com"
          single-commit: true




