name: Lint VC Vocabulary
on:
  pull_request:
    paths:
    - 'vocab/credentials/v2/vocabulary.yml'
    - 'vocab/credentials/v2/template.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout/@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Lint VC vocabularies
        run: |
          npm install yml2vocab
          npm update yml2vocab
          ./node_modules/.bin/yml2vocab -v vocab/credentials/v2/vocabulary.yml -t vocab/credentials/v2/template.html
